Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,22 +1,20 @@
 name: CI
- 
+
 on:
   push:
     branches: [ "main" ]
   pull_request:
     branches: [ "main" ]
   workflow_dispatch:
- 
+
 jobs:
   build:
     runs-on: ubuntu-latest
- 
+
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
- 
-    
- 
+
       - name: Install Apache JMeter
         run: |
           wget -q https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz
@@ -24,23 +22,33 @@ jobs:
           mv apache-jmeter-5.4.1 $HOME/apache-jmeter
           rm apache-jmeter-5.4.1.tgz
           chmod +x $HOME/apache-jmeter/bin/jmeter
- 
+
       - name: Create reports directory
         run: mkdir -p reports/html
- 
+
       - name: JMeter Test
         run: $HOME/apache-jmeter/bin/jmeter -n -t webTours.jmx -l result.jtl
- 
+
+      - name: Check if result.jtl exists
+        run: |
+          if [ ! -f "result.jtl" ]; then
+            echo "result.jtl not found!"
+            exit 1
+          fi
+
       - name: Generate HTML Report
         run: $HOME/apache-jmeter/bin/jmeter -g result.jtl -o ./reports/html/
- 
+
+      - name: List report directory contents for debug
+        run: ls -la ./reports/html/
+
       - name: Upload Results
         uses: actions/upload-artifact@v3
         with:
           name: jmeter-results
           path: result.jtl
           if-no-files-found: error
- 
+
       - name: Upload HTML Reports
         uses: actions/upload-artifact@v3
         with:
